---
title: "Analyse comparative des réseaux de collaboration entre les étudiants du cours BIO500 et les réseaux écologiques"
author: Ariane Barrette, Mia Carrière, Laurie-Anne Cournoyer & Marie-Claude Mayotte
output: html_document
date: "2023-04-22"
bibliography: bio500.bib
---
# Résumé 

Les réseaux écologiques peuvent être utilisés dans le but de comprendre les interactions entre les différentes espèces d’une communauté écologique. Ainsi, cet article vise à comparer les réseaux de collaboration entre les étudiants du cours de méthodes en écologie computationnelle (BIO500) à ceux des réseaux écologiques. Trois questions de recherches furent élaborées afin d’atteindre l’objectif principale de cet article. Une campagne de collecte de données avec la coopération de tous les étudiants du cours a d’abord été créé afin de concevoir trois bases de données (collaboration, étudiant et cours). Une analyse des trois bases de données a été effectué afin de réaliser trois figures à l’aide de différentes librairies dans RStudio. Les résultats montrent que la centralité est un concept important dans les réseaux écologiques et peut également être utilisés dans le contexte scolaire. En effet, elle permet d’identifier les étudiants « clés » dans le réseau de collaboration des étudiants. De plus, les résultats permettent de constater que les étudiants ont interagis davantage avec les zones centrales comme Montréal, Sherbrooke ou Trois-Rivières quel que soit leur région administrative d’origine.

# Introduction 
Dans une communauté écologique, différentes espèces interagissent ensemble. L’interaction entre ces espèces peut mener à produire différents modèles de réseau. En effet, au sein des réseaux écologiques, l’organisation et la position des espèces dans la communauté peuvent être déterminées [@delmas_analysing_2019]. Les réseaux écologiques des espèces peuvent également s’appliquer à d’autres contextes. L’objectif principal de cet article vise à comparer les réseaux de collaboration entre les étudiants du cours de méthodes en écologie computationnelle à ceux des réseaux écologiques. L’atteinte de cet objectif permettra de mieux comprendre les différences entre les propriétés des réseaux des étudiants en écologie et celles des réseaux écologiques. Ainsi, pour notre projet, trois questions de recherches ont été élaborées : (1) « Peut-on observer un patron de centralité entre les étudiants d'une classe en analysant leurs interactions dans les travaux scolaires ? », (2) « Retrouve-t-on des patrons d’interactions entre les élèves basé sur leur formation préalable et leur année d’admission au baccalauréat ? », (3) « Comment les relations entre les élèves d'une classe varient-elles en fonction de leur région administrative ?.». Afin de répondre à ces différentes questions de recherches, une analyse collaborative sur la plateforme GitHub a été réalisé à l’aide de Rstudio.

# Méthode et résultats

Afin de répondre à ces questions de recherche, une campagne de collecte de données a été réalisée en collaboration avec tous les étudiants du cours de méthodes computationnelles afin de créer trois bases de données (collaboration, étudiant et cours). Afin d’analyser ces données, un projet collaboratif sur la plateforme GitHub a été créé. À partir de cette plateforme et par l’entremise de Rstudio, le nettoyage des données, la création des figures et du target ont été réalisés. En ce qui concerne le target, c’est la librairie RSQLite qui a été utilisée. Pour terminer, l’article a été réalisé à l’aide de Rmarkdown. 

D’ailleurs, afin d’illustrer la centralité des étudiants, la figure 1 a été créée à l’aide des librairies htmlwidgets, webshot, ggplot2, igraph et fields de R. Elle représente le nombre de collaborations différentes effectuées par chaque étudiant. L’étudiant ayant réalisé le plus de collaborations s’attribuant le rang le plus élevée (le rang 162) et étant l’étudiant le plus central. Les figures 2 et 3 ont été réalisés à l’aide de la librairie gplots dans R. Elles représentent la moyenne du nombre de collaborations selon leur parcours éducatif et selon leur année d’entrée au baccalauréat.  La barre la plus grande représente la catégorie ayant eu le plus de collaborations avec différents étudiants. La figure 4 représente les collaborations entre les étudiants en fonction de leur région native. Elle a été réalisée à l’aide des librairies leaflet et leaflegend de R. Les lignes les plus épaisses représentent les régions ayant eu le plus de collaborations entre-elles. 

# Résultats

```{r, echo=FALSE}
donnees_net <- tar_read(data)
etudiant <- donnees_net[[1]]

donnees <- tar_read(req_sql)
nb_paire_colla <- donnees[[4]]

# Créer la matrice
r<-nrow(etudiant)
matrice_interact <- matrix(0, nr = r, nc = r)
noms<-etudiant[, 1]

# Attribuer les noms de colonnes et de lignes à la matrice
colnames(matrice_interact)<-noms
rownames(matrice_interact)<-noms

# Créer une boucle pour insérer des 1 quand les deux étudiants ont eu une interaction
n<-nrow(nb_paire_colla)
for (i in 1:n){
  if (nb_paire_colla[i,3]>0) {
  matrice_interact[nb_paire_colla[i,1],nb_paire_colla[i,2]]<-1 }
}  
# Créer un objet igraph
g <- graph.adjacency(matrice_interact)
deg <- apply(matrice_interact, 2, sum) + apply(matrice_interact, 1, sum)
# Le rang pour chaque noeud
rk <- rank(deg)
# Faire un code de couleur
col.vec <- heat.colors(r)
# Attribuer aux noeuds la couleur
V(g)$color = col.vec[rk]
#Taille
col.vec <- seq(1, 5, length.out = r)
# Attribuer aux noeuds la couleur
V(g)$size = col.vec[rk]

#Réalisation de la figure
figure1<- plot(g,vertex.label = NA, edge.arrow.mode = 0,
     vertex.frame.color = NA,
     layout = layout.kamada.kawai(g))

# Définir le gradient de couleur pour la légende
color_gradient <- colorRampPalette(heat.colors(r))(100)

# Définir le range de couleur
color_range <- range(1:r)

# Ajouter la légende et un titre de figure
par(mar=c(5,4,4,8))
image.plot(legend.only = TRUE, horizontal=TRUE, zlim=color_range,col=color_gradient)
title("Réseau d'interactions entre les étudiants", line = 1, cex.main = 1.2)
mtext("Rang des étudiants", side = 1, line = 1, cex = 1)
```

Figure 1 : Réseau d'interaction entre les étudiants. Les points blancs représentes les étudiants les plus centraux alors que les points rouges représentrent les étudiants les moins centraux, c'est-à-dire ceux qui ont collaboré avec le moins de mondes.

![Figure 2 : Nombre de collaborations des différents élèves de méthodes computationnelles selon la formation préalable avant l’entrée au baccalauréat.La barre représente l’écart-type. 
\label{fig:plot2}](barplot_annee.PNG){width="45%"
height="20%"}



![Figure 3: Nombre de collaborations des différents élèves de méthodes computationnelles selon l’année d’entrée au baccalauréat.
\label{fig:plot3}](barplot_formation.PNG){width="45%"
height="20%"}



![Figure 4 : Collaborations entre les différents élèves du cours de méthodes computationnelles selon leur région administratives d’origine.Les lignes représentent les collaborations entre deux élèves, plus la ligne est épaisse et plus il y a eu de collaborations entre ces deux régions.
\label{fig:plot4}](carte_liens.PNG){width="45%"
height="20%"}


# Discussion

## Centralité
La centralité est un concept important dans les réseaux écologiques puisqu’elle est souvent utiliser afin d’identifier les espèces « clés » du système [@cagua_keystoneness_2019].  En effet, selon ce principe, les espèces participants dans plus de chaines sont plus susceptibles d’affecter l’abondance des autres espèces [@cagua_keystoneness_2019]. De plus, elle peut apporter de l’information pour prédire quelle espèce, si elle venait à disparaître, aurait le plus grand impact sur la communauté [@cagua_keystoneness_2019]. Toutefois, il faut apporter la nuance que la centralité ne parvient pas à identifier les espèces qui sont moins connectés, mais qui ont tout de même une grande capacité de contrôle sur la communauté [@cagua_keystoneness_2019]. Dans le cas de cette expérience, il est premièrement possible d’observer un patron de centralité entre les étudiants en analysant leurs interactions dans les travaux scolaires. En effet, les étudiants ayant collaborés avec un grand nombre de personnes différentes sont représentés comme étant des étudiants centraux. En interagissant avec une grande partie du réseau, ces étudiants ont un impact significatif sur l'abondance des autres élèves, qui dans ce contexte peut être représentée par leurs notes scolaires, établissant ainsi un lien avec les systèmes écologiques. 
Par ailleurs, ce réseau prend seulement en compte les interactions entre les élèves de la classe. Toutefois, plusieurs élèves ont interagi, au cours de leur baccalauréat, avec des étudiants ne se sont pas dans ce cours. Par conséquent, ces étudiants font donc partie d’un autre réseau et la centralité ne nous permet donc pas d’évaluer adéquatement leur importance. 

## Patrons d’interactions
Tous les réseaux écologiques, même les plus hétérogènes, présentent certaines structures et regroupements d’interactions entre les nœuds  [@delmas_analysing_2019; @milo_network_2002]. En fait, il existe 13 patrons possibles pour une interaction à trois nœuds chacun représentant une relation différente  [@delmas_analysing_2019; @milo_network_2002]. Par exemple, il y a la concurrence entre A et B pour la ressource partagée C (A -> C <- B) ou une chaine alimentaire où A prédate B et B prédate C (A -> B -> C) [@delmas_analysing_2019; @milo_network_2002]. En se basant sur la formation préalable des étudiants, on peut observer que les étudiants ayant une formation universitaire sont plus susceptible de travailler avec un plus grand nombre de personnes différentes que les personnes ayant une formation technicienne. De plus, les étudiants qui sont rentrés au baccalauréat en écologie en hiver 2019 ont travaillé avec un plus grand nombre de personnes que ceux des autres sessions d’admission et cela malgré qu’ils soient beaucoup moins que les étudiants à être rentrés à l’automne 2020. Cela est assez logique puisque ces étudiants ont un parcours différent et par conséquent, ils doivent souvent collaborés avec d’autres cohortes. Il est donc possible d’observer certains patrons d’interactions entre les élèves.  

Toutefois, ces résultats sont surtout préliminaires puisqu’ils ne tiennent pas compte de la proportion d’étudiants dans chaque catégorie. Par exemple, comme il y a moins d’étudiants qui ont une formation technicienne que pré-universitaire, il est logique qu’il possède un nombre d’interactions inférieurs aux autres catégories. Pour avoir un meilleur aperçu des regroupements, il faudrait pondérer les moyens de chaque catégorie. 

## Connectivité des régions administratives
 Pour assurer la survie des espèces, il est crucial d'évaluer leur connectivité entre les différentes zones géographiques [@baguette_individual_2013]. En effet, la disparition d'une population locale peut précéder l'extinction de l'espèce dans son ensemble [@baguette_individual_2013]. De plus, certaines espèces jouent un rôle central dans le réseau écologique, ce qui signifie que leur disparition peut entraîner des conséquences importantes sur d'autres espèces et sur la stabilité de l'écosystème [@baguette_individual_2013]. Il est donc important de prendre en compte à la fois la connectivité des habitats et le rôle des espèces centrales pour maintenir la biodiversité [@baguette_individual_2013].

En observant les interactions entre les élèves, la région de Montréal apparaît comme la zone centrale la plus peuplée en termes d'étudiants, ce qui est cohérent étant donné qu'elle est la région la plus densément peuplée du Québec [@gouvernement_du_canada_les_2022]. De plus, la zone avec la dispersion la plus importante, caractérisée ici par les interactions entre les étudiants, se situe entre Montréal et Sherbrooke. Il semble y avoir un patron montrant que la majorité des étudiants, quelle que soit leur région administrative, ont tendance à interagir plus fréquemment avec les zones centrales telles que Montréal, Sherbrooke et Trois-Rivières, plutôt qu'avec les zones situées à proximité. Pour établir un parallèle avec le réseau écologique, cette observation pourrait être attribuée à la présence d'étudiants clés dans ces régions. 

Bref, le réseaux étudiants ressemblent sur plusieurs points aux réseaux écologiques par sa centralité, ses patrons d’assemblages et par la connectivité des régions administratives.

#### Lien vers le github
https://github.com/mcmayotte/projet_bio500.git


# Bibliographie